analysis/urls.py
from django.urls import path, include
from .views import EntryListView, DayDetailView, EntryDetailView

urlpatterns = [
    path('',EntryListView.as_view(), name='analysis-home'),
    path('day/<int:pk>/',DayDetailView.as_view(), name='analysis-day-detail'),
    path('entry/<int:pk>/',EntryDetailView.as_view(), name='analysis-entry-detail'),
    path('automated/', include('automated.urls')),
    path('manual/', include('manual.urls'))
]

capstone_412002117_software/urls.py
"""capstone_412002117_software URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('analysis/', include('analysis.urls')),
    path('analysis_statistics/', include('analysis_statistics.urls')),
    path('psa/', include('psa.urls')),
    
    path('', include('psa.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='psa-home'),
    path('add_day/<path:sub_dir>/', views.add_day, name='psa-add-day'),
    path('add_days/', views.add_days, name='psa-add-days'),
    path('open_file/<path:filepath>/', views.open_file, name='psa-open-file'),
    path('populate_tables/', views.populate_tables, name='psa-populate-tables'),
    path('auto_analyze_day/', views.auto_analyze_day, name='psa-auto-analyze-day'),
    path('auto_analyze_days/', views.auto_analyze_days, name='psa-auto-analyze-days'),
]

analysis/models.py
"""Has the models for the analysis app.
"""

from django.db import models
from django.urls import reverse

class Day(models.Model):
    """Class representing a day. Subclass of :class:`django.db.models.Model`. 
    """

    date = models.DateField()
    """(DateField) the day's date"""

    tried_feed_in = models.BooleanField(default=False, help_text='Tried to feed iai extracted image into pr analysis?')
    """(BooleanField) whether or not an attempt was made to feed the images extracted during the Imageai analysis into the Plate Recognizer analysis, defaults to False"""

    json_file = models.FileField( max_length=250, blank=True, null=True)
    """(FileField) the JSON file associated with the day"""
    
    log_file = models.FileField(max_length=250, blank=True, null=True)
    """(FileField) the log file associated with the day"""

    class Meta:
        """Adds metadata about the Day model class (used in admin section)
        """

        verbose_name = 'day'
        """(str) the name of the model class"""

        verbose_name_plural = 'days'
        """(str) the plural version of the name of the model class"""
        

    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object 
                 (format = '%b %d, %Y' = abbreviated month: zero padded decimal day of the month: year with century as a decimal number)  
        :rtype: str
        """

        return self.date.strftime('%b %d, %Y')

    def get_absolute_url(self):
        """ Tells Django how to calculate the canonical URL for an object

        :return: the url to the analysis day detail for the particular day  
        :rtype: str  
        """

        return reverse('analysis-day-detail', kwargs={'pk': self.pk})

class Entry(models.Model):
    """Class representing a day's entry. Subclass of :class:`django.db.models.Model`.  
    """

    arrival_time = models.DateTimeField()
    """(DateField) the entry's arrival time"""

    departure_time = models.DateTimeField()
    """(DateTimeField) the entry's departure time"""

    status = models.CharField(max_length=30, default='needs automated analysis')
    """(CharField) the entry's status, defaults to 'needs automated analysis', updated by signals"""

    day = models.ForeignKey(Day,on_delete=models.CASCADE, related_name='entries')
    """(ForeignKey) the entry's day \(:class:`analysis.models.Day`\)"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object  (arrival time of the entry) 
                 (format = '%I:%M:%S %p' = 
                 Hour (12-hour clock) as a zero-padded decimal number : Minute as a zero-padded decimal number : Second as a zero-padded decimal number : either AM or PM)  
        :rtype: str
        """

        return self.arrival_time.strftime('%I:%M:%S %p')

    def get_absolute_url(self):
        """ Tells Django how to calculate the canonical URL for an object

        :return: the url to the analysis entry detail for the particular entry  
        :rtype: str  
        """

        return reverse('analysis-entry-detail', kwargs={'pk': self.pk})

class DayTiming(models.Model):
    """Class representing a day's timing. Subclass of :class:`django.db.models.Model`.  
    """

    day = models.OneToOneField(Day,on_delete=models.CASCADE, related_name='daytiming')
    """(OneToOneField) the day associated with the timing data  \(:class:`analysis.models.Day`\)"""

    total_get_duration_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.get_duration` function"""

    total_imageai_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_detect` function"""

    total_imageai_prediction_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_predict` function  when called with the Imageai extracted images"""

    total_imageai_colour_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.detect_colours` function  when called with the Imageai extracted images"""

    total_imageai_analysis_time = models.DurationField()
    """(DurationField) total time taken for Imageai analysis"""

    total_pr_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.plate_recognizer_detect` function"""

    total_pr_prediction_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_predict` function  when called with the  plate recognizer extracted images"""

    total_pr_colour_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.detect_colours` function  when called with the  plate recognizer extracted image"""

    total_pr_analysis_time = models.DurationField()
    """(DurationField) total time taken for Plate Recognizer analysis"""

    total_image_analysis_time = models.DurationField()
    """(DurationField) total time to analyze all the images"""

    total_entry_time = models.DurationField()
    """(DurationField) total time to analyze all the entries"""

    total_day_time = models.DurationField()
    """(DurationField) total time to process the entire day (analyze entries, setup and move files, etc.)"""


    class Meta:
        """Adds metadata about the DayTiming model class (used in admin section)
        """

        verbose_name = 'day timing'
        """(str) the name of the model class"""

        verbose_name_plural = 'day timings'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (the total day time value)  
        :rtype: str  
        """

        return str(self.total_day_time)

automated/models.py
"""Has the models for the automated app.
"""

from django.db import models
from analysis.models import Entry

class AutomatedAnalysis(models.Model):
    """Class representing an automated analysis (has the basic info for an automated analysis). Subclass of :class:`django.db.models.Model`.  
    """

    
    entry = models.OneToOneField(Entry,on_delete=models.CASCADE, related_name='automatedanalysis')
    """(OneToOneField) the automated analysis' entry \(:class:`analysis.models.Entry`\)"""

    duration = models.DurationField()
    """(DurationField) the automatically calculated duration"""

    successful_feed_in = models.BooleanField(blank=True, null=True,help_text='Was iai extracted image successfully fed into pr analysis (image with imageai_pr in name produced)?')
    """(BooleanField) whether or not the image extrcaten during Imageai analysis was successfully fed into the Plate Recognizer analysis"""


    class Meta:
        """Adds metadata about the AutomatedAnalysis model class (used in admin section) 
        """

        verbose_name = 'automated analysis'
        """(str) the name of the model class"""
        verbose_name_plural = 'automated analyses'
        """(str) the plural version of the name of the model class"""

    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (arrival time of the entry) 
                 (format = '%I:%M:%S %p' = 
                 Hour (12-hour clock) as a zero-padded decimal number : Minute as a zero-padded decimal number : Second as a zero-padded decimal number : either AM or PM)  
        :rtype: str
        """

        return self.entry.arrival_time.strftime('%I:%M:%S %p')


class Image(models.Model):
    """Class representing an image. Subclass of :class:`django.db.models.Model`.
    """

    image = models.ImageField(default='default.jpg', max_length=250)
    """(ImageField) the image, defaults to 'default.jpg'"""

    type = models.ForeignKey('psa.ImageType',on_delete=models.CASCADE)
    """(ForeignKey) the image's type \(:class:`psa.models.ImageType`\)"""

    entry = models.ForeignKey(Entry,on_delete=models.CASCADE, related_name='images')
    """(ForeignKey) the entry associated with the image \(:class:`analysis.models.Entry`\)"""


    class Meta:
        """Adds metadata about the Image model class (used in admin section) 
        """        
        verbose_name = 'image'
        """(str) the name of the model class"""

        verbose_name_plural = 'images'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (image's url)  
        :rtype: str
        """

        return self.image.url


class IaiVehicleDetection(models.Model):
    """Class representing an Imageai Vehicle Detection. Subclass of :class:`django.db.models.Model`.  
    """

    automated_analysis = models.OneToOneField(AutomatedAnalysis, on_delete=models.CASCADE, related_name='iaivehicledetection')
    """(OneToOneField) the automated analysis associated with the Imageai Vehicle Detection \(:class:`automated.models.AutomatedAnalysis`\)"""

    type = models.ForeignKey('psa.IaiDetectionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Imageai Vehicle Detection class detected \(:class:`psa.models.IaiDetectionClass`\)"""

    probability = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    """(DecimalField) the probability that the correct Imageai Vehicle Detection class was detected, defaults to 0.00"""


    class Meta:
        """Adds metadata about the IaiVehicleDetection model class (used in admin section)
        """ 

        verbose_name = 'imageai vehicle detection'
        """(str) the name of the model class"""

        verbose_name_plural = 'imageai vehicle detections'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (Imageai Detection class' name)  
        :rtype: str
        """

        return self.type.name

class IaiVehiclePrediction(models.Model):
    """Class representing an Imageai Vehicle Prediction. Subclass of :class:`django.db.models.Model`.  
    """
        
    automated_analysis = models.OneToOneField(AutomatedAnalysis, on_delete=models.CASCADE, related_name='iaivehicleprediction')
    """(OneToOneField) the automated analysis associated with the Imageai Vehicle Prediction \(:class:`automated.models.AutomatedAnalysis`\)"""

    type = models.ForeignKey('psa.PredictionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Prediction class identified during the Imageai analysis \(:class:`psa.models.PredictionClass`\)"""

    probability = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    """(DecimalField) the probability that the correct Prediction class was identified during the Imageai analysis, defaults to 0.00"""


    class Meta:
        """Adds metadata about the IaiVehiclePrediction model class (used in admin section)
        """ 

        verbose_name = 'imageai vehicle prediction'
        """(str) the name of the model class"""

        verbose_name_plural = 'imageai vehicle predictions'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (name of prediction class identified during the Imageai analysis)  
        :rtype: str
        """

        return self.type.name

class IaiColourDetection(models.Model):
    """Class representing an Imageai Colour Detection. Subclass of :class:`django.db.models.Model`.  
    """

    automated_analysis = models.ForeignKey(AutomatedAnalysis, on_delete=models.CASCADE, related_name='iaicolourdetections')
    """(ForeignKey) the automated analysis associated with the Imageai Colour Detection \(:class:`automated.models.AutomatedAnalysis`\)"""

    colour = models.ForeignKey('psa.Colour', on_delete=models.PROTECT)
    """(ForeignKey) the colour in the database that's closest to the detected colour \(:class:`psa.models.Colour`\)"""

    percentage = models.DecimalField(max_digits=29, decimal_places=26, default=100)
    """(DecimalField) the percentage of the image the colour takes up, defaults to 100"""

    detected_r = models.IntegerField()
    """(IntegerField) the detected red value of the colour"""

    detected_g = models.IntegerField()
    """(IntegerField) the detected green value of the colour"""

    detected_b = models.IntegerField()
    """(IntegerField) the detected blue value of the colour"""

    detected_hex = models.CharField(max_length=7)
    """(CharField) the detected hex value of the colour"""


    class Meta:
        """Adds metadata about the IaiColourDetection model class (used in admin section)
        """ 
        
        verbose_name = 'imageai colour detection'
        """(str) the name of the model class"""

        verbose_name_plural = 'imageai colour detections'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (colour's name)  
        :rtype: str
        """

        return self.colour.name


class PrVehicleDetection(models.Model):
    """Class representing a Pr Vehicle Detection. Subclass of :class:`django.db.models.Model`.   
    """

    
    automated_analysis = models.OneToOneField(AutomatedAnalysis, on_delete=models.CASCADE, related_name='prvehicledetection')
    """(OneToOneField) the automated analysis associated with the Pr Vehicle Detection \(:class:`automated.models.AutomatedAnalysis`\)"""

    type = models.ForeignKey('psa.PrDetectionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Pr Vehicle Detection class detected \(:class:`psa.models.PrDetectionClass`\)"""

    probability = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    """(DecimalField) the probability that the correct Pr Vehicle Detection class was detected, defaults to 0.00"""


    class Meta:
        """Adds metadata about the PRVehicleDetection model class (used in admin section)
        """ 

        
        verbose_name = 'plate recognizer vehicle detection'
        """(str) the name of the model class"""

        verbose_name_plural = 'plate recognizer vehicle detections'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (PR Detection class' name)  
        :rtype: str
        """
        
        return self.type.name

class PrVehiclePrediction(models.Model):
    """Class representing a PR Vehicle Prediction. Subclass of :class:`django.db.models.Model`.  
    """
        
    automated_analysis = models.OneToOneField(AutomatedAnalysis, on_delete=models.CASCADE, related_name='prvehicleprediction')
    """(OneToOneField) the automated analysis associated with the PR Vehicle Prediction \(:class:`automated.models.AutomatedAnalysis`\)"""

    type = models.ForeignKey('psa.PredictionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Prediction class identified during the PR analysis \(:class:`psa.models.PredictionClass`\)"""

    probability = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    """(DecimalField) the probability that the correct Prediction class was identified during the PR analysis, defaults to 0.00"""


    class Meta:
        """Adds metadata about the PRVehiclePrediction model class (used in admin section)
        """ 

        
        verbose_name = 'plate recognizer vehicle prediction'

analysis/templates/analysis/day_detail.html
{% extends "psa/layouts/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load index %}

{% block head_content %}
    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    
{% endblock head_content %}

{% block content %} 

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%  url 'psa-home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'analysis-home' %}">Analysis</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ day.date|date:"F j, Y" }}</li>
        </ol>
    </nav>


    <div class="card bg-light">
        <div class="card-header row align-items-center">
            {% with tables|index:0 as table %}
                <div class="col" >
                    <h2>
                        {{ day.date|date:"F j, Y" }} Analysis Summary 
                        {% if day.tried_feed_in %}
                            (tried feed in) 
                        {% else %}
                            (didn't try feed in) 
                        {% endif %}
                        ({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})
                    </h2>
                </div>
            {% endwith %}

            <div class="text-right">
                <a href="{% url 'automated-day-detail' day.id %}" class="btn btn-sm btn-primary" title='View All Auto Analyses'><i class="fas fa-eye"></i></a>
                <a href="{% url 'manual-day-detail' day.id %}" class="btn btn-sm btn-secondary" title='View All Manual Analyses'><i class="fas fa-eye"></i></a>
                <a href="{% url 'analysis_statistics-home' %}?date_after={{ day.date|date:'Y-m-d' }}&date_before={{ day.date|date:'Y-m-d' }}" class="btn btn-sm btn-secondary" title='View Statistics'><i class="fas fa-chart-bar"></i></a>
                <a href="{% url 'psa-open-file' day.json_file.url %}" target="_blank" class="btn btn-sm btn-secondary" title='View JSON'><i class="fas fa-file"></i></a>
                <a href="{% url 'psa-open-file' day.log_file.url %}" class="btn btn-sm btn-secondary" title='View Log'><i class="far fa-file"></i></a>
            </div>
        </div>            
        
        <div class="card-body">
            <ul class="nav nav-tabs nav-justified" id="analysisDayDetailTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="entry-info-tab" data-toggle="tab" href="#entry-info" role="tab" aria-controls="entry-info" aria-selected="true">Entry Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="entry-timing-tab" data-toggle="tab" href="#entry-timing" role="tab" aria-controls="entry-timing" aria-selected="false">Entry Timing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="day-timing-tab" data-toggle="tab" href="#day-timing" role="tab" aria-controls="day-timing" aria-selected="false">Day Timing</a>
                </li>
            </ul>


            <div class="tab-content" id="analysisDayDetailTabContent">
                <div class="tab-pane fade show active" id="entry-info" role="tabpanel" aria-labelledby="entry-info-tab">
                    {% if filter %}
                        <form action="" method="get" class="form form-inline">
                            {{ filter.form|crispy }}
                            <a href="{%  url 'analysis-day-detail' day.id %}">Clear all filters</a>
                            <input type="submit" />
                        </form>
                    {% endif %}
                    
                    {% with tables|index:0 as table %}
                        {% if table != None %}
                            {%  render_table table %}
                            
                            <div class="text-center">
                                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
                            </div>
                                
                        {% else %}
                            <h2>NO DATA</h2>
                        {% endif %}
                    {% endwith %}
                </div>

                <div class="tab-pane fade" id="entry-timing" role="tabpanel" aria-labelledby="entry-timing-tab">
                    {% with tables|index:1 as table %}
                        {% if table != None %}
                            {%  render_table table %}
                            
                            <div class="text-center">
                                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
                            </div>
                                
                        {% else %}
                            <h2>NO DATA</h2>
                        {% endif %}
                    {% endwith %}
                </div> 

                <div class="tab-pane fade" id="day-timing" role="tabpanel" aria-labelledby="day-timing-tab">
                    {% include 'psa/partials/day_timing_section.html' %}
                </div>

            </div>

        </div>

    </div>


{% endblock content %}

{% block script_content %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_successful_feed_in').select2();
            $('#id_status').select2();
            $('#id_automated_iaivehicledetection').select2();
            $('#id_automated_iaivehicleprediction').select2();
            $('#id_automated_prvehicledetection').select2();
            $('#id_automated_prvehicleprediction').select2();
            $('#id_manual_iaivehicledetection').select2();
            $('#id_manual_prvehicledetection').select2();
            $('#id_manual_prediction').select2();

        });
    </script>
{% endblock script_content%}

analysis/templates/analysis/home.html
{% extends "psa/layouts/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}

{% block head_content %}
    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    
{% endblock head_content %}

{% block content %} 

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%  url 'psa-home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Analysis</li>
        </ol>
    </nav>

    <div class="card bg-light">
        <div class="card-header row align-items-center">
            <div class="col" ><h2>Analysis Home ({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h2></div>

            <div class="ml-2 col text-right">
                <a href="{% url 'automated-home' %}" class="btn btn-sm btn-primary" title='View All Auto Analyses'><i class="fas fa-eye"></i></a>
                <a href="{% url 'manual-home' %}" class="btn btn-sm btn-secondary" title='View All Manual Analyses'><i class="far fa-eye"></i></a>
                <a href="{% url 'analysis_statistics-home' %}" class="btn btn-sm btn-secondary" title='View All Statistics'><i class="fas fa-chart-bar"></i></a>
            </div>

        </div>            
        
        <div class="card-body">
            {% if filter %}
                <form action="" method="get" class="form form-inline">
                    {{ filter.form|crispy }}
                    <a href="{%  url 'analysis-home' %}">Clear all filters</a>
                    <input type="submit" />
                </form>
            {% endif %}

            {% if table != None %}
                {%  render_table table %}
            {% else %}
                <h2>NO DATA</h2>
            {% endif %}

            <div class="text-center">
                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
            </div>
        </div>
    </div>


{% endblock content %}

{% block script_content %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_tried_feed_in').select2();
            $('#id_successful_feed_in').select2();
            $('#id_status').select2();
            $('#id_automated_iaivehicledetection').select2();
            $('#id_automated_iaivehicleprediction').select2();
            $('#id_automated_prvehicledetection').select2();
            $('#id_automated_prvehicleprediction').select2();
            $('#id_manual_iaivehicledetection').select2();
            $('#id_manual_prvehicledetection').select2();
            $('#id_manual_prediction').select2();

        });
    </script>
{% endblock script_content%}