capstone_412002117_software/urls.py
"""capstone_412002117_software URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('analysis/', include('analysis.urls')),
    path('analysis_statistics/', include('analysis_statistics.urls')),
    path('psa/', include('psa.urls')),
    
    path('', include('psa.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manual/urls.py
from django.urls import path, include
from .views import EntryListView, EntryDetailView, DayDetailView, ManualAnalysisCreateView, ManualAnalysisUpdateView

urlpatterns = [
    path('',EntryListView.as_view(), name='manual-home'),
    path('day/<int:pk>/',DayDetailView.as_view(), name='manual-day-detail'),
    path('entry/<int:pk>/',EntryDetailView.as_view(), name='manual-entry-detail'),
    path('new/<int:pk>/', ManualAnalysisCreateView.as_view(), name='manual-create'),
    path('entry/<int:pk>/update/', ManualAnalysisUpdateView.as_view(), name='manual-update'),
]

psa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='psa-home'),
    path('add_day/<path:sub_dir>/', views.add_day, name='psa-add-day'),
    path('add_days/', views.add_days, name='psa-add-days'),
    path('open_file/<path:filepath>/', views.open_file, name='psa-open-file'),
    path('populate_tables/', views.populate_tables, name='psa-populate-tables'),
    path('auto_analyze_day/', views.auto_analyze_day, name='psa-auto-analyze-day'),
    path('auto_analyze_days/', views.auto_analyze_days, name='psa-auto-analyze-days'),
]

analysis/models.py
"""Has the models for the analysis app.
"""

from django.db import models
from django.urls import reverse

class Day(models.Model):
    """Class representing a day. Subclass of :class:`django.db.models.Model`. 
    """

    date = models.DateField()
    """(DateField) the day's date"""

    tried_feed_in = models.BooleanField(default=False, help_text='Tried to feed iai extracted image into pr analysis?')
    """(BooleanField) whether or not an attempt was made to feed the images extracted during the Imageai analysis into the Plate Recognizer analysis, defaults to False"""

    json_file = models.FileField( max_length=250, blank=True, null=True)
    """(FileField) the JSON file associated with the day"""
    
    log_file = models.FileField(max_length=250, blank=True, null=True)
    """(FileField) the log file associated with the day"""

    class Meta:
        """Adds metadata about the Day model class (used in admin section)
        """

        verbose_name = 'day'
        """(str) the name of the model class"""

        verbose_name_plural = 'days'
        """(str) the plural version of the name of the model class"""
        

    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object 
                 (format = '%b %d, %Y' = abbreviated month: zero padded decimal day of the month: year with century as a decimal number)  
        :rtype: str
        """

        return self.date.strftime('%b %d, %Y')

    def get_absolute_url(self):
        """ Tells Django how to calculate the canonical URL for an object

        :return: the url to the analysis day detail for the particular day  
        :rtype: str  
        """

        return reverse('analysis-day-detail', kwargs={'pk': self.pk})

class Entry(models.Model):
    """Class representing a day's entry. Subclass of :class:`django.db.models.Model`.  
    """

    arrival_time = models.DateTimeField()
    """(DateField) the entry's arrival time"""

    departure_time = models.DateTimeField()
    """(DateTimeField) the entry's departure time"""

    status = models.CharField(max_length=30, default='needs automated analysis')
    """(CharField) the entry's status, defaults to 'needs automated analysis', updated by signals"""

    day = models.ForeignKey(Day,on_delete=models.CASCADE, related_name='entries')
    """(ForeignKey) the entry's day \(:class:`analysis.models.Day`\)"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object  (arrival time of the entry) 
                 (format = '%I:%M:%S %p' = 
                 Hour (12-hour clock) as a zero-padded decimal number : Minute as a zero-padded decimal number : Second as a zero-padded decimal number : either AM or PM)  
        :rtype: str
        """

        return self.arrival_time.strftime('%I:%M:%S %p')

    def get_absolute_url(self):
        """ Tells Django how to calculate the canonical URL for an object

        :return: the url to the analysis entry detail for the particular entry  
        :rtype: str  
        """

        return reverse('analysis-entry-detail', kwargs={'pk': self.pk})

class DayTiming(models.Model):
    """Class representing a day's timing. Subclass of :class:`django.db.models.Model`.  
    """

    day = models.OneToOneField(Day,on_delete=models.CASCADE, related_name='daytiming')
    """(OneToOneField) the day associated with the timing data  \(:class:`analysis.models.Day`\)"""

    total_get_duration_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.get_duration` function"""

    total_imageai_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_detect` function"""

    total_imageai_prediction_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_predict` function  when called with the Imageai extracted images"""

    total_imageai_colour_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.detect_colours` function  when called with the Imageai extracted images"""

    total_imageai_analysis_time = models.DurationField()
    """(DurationField) total time taken for Imageai analysis"""

    total_pr_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.plate_recognizer_detect` function"""

    total_pr_prediction_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.imageai_predict` function  when called with the  plate recognizer extracted images"""

    total_pr_colour_detection_time = models.DurationField()
    """(DurationField) total time taken to run the :func:`spot_analysis.detect_colours` function  when called with the  plate recognizer extracted image"""

    total_pr_analysis_time = models.DurationField()
    """(DurationField) total time taken for Plate Recognizer analysis"""

    total_image_analysis_time = models.DurationField()
    """(DurationField) total time to analyze all the images"""

    total_entry_time = models.DurationField()
    """(DurationField) total time to analyze all the entries"""

    total_day_time = models.DurationField()
    """(DurationField) total time to process the entire day (analyze entries, setup and move files, etc.)"""


    class Meta:
        """Adds metadata about the DayTiming model class (used in admin section)
        """

        verbose_name = 'day timing'
        """(str) the name of the model class"""

        verbose_name_plural = 'day timings'
        """(str) the plural version of the name of the model class"""


    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (the total day time value)  
        :rtype: str  
        """

        return str(self.total_day_time)

manual/models.py
"""Has the model for the manual app (ManualAnalysis) and a class that has a function to get the data the view needs to pass to the form in the 
manualanalysis_form.html template.
"""

from django.db import models
from django.urls import reverse
from analysis.models import Entry

class ManualAnalysis(models.Model):
    """Class representing a manual analysis (has all the info for a manual analysis). Subclass of :class:`django.db.models.Model`.
    """

    entry = models.OneToOneField(Entry,on_delete=models.CASCADE, related_name='manualanalysis')
    """(OneToOneField) the manual analysis' entry \(:class:`analysis.models.Entry`\)"""
    
    duration = models.DurationField()
    """(DurationField) the manually calculated duration"""
    
    iai_detection_class = models.ForeignKey('psa.IaiDetectionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Imageai Vehicle Detection class identified \(:class:`psa.models.IaiDetectionClass`\)"""
    
    pr_detection_class = models.ForeignKey('psa.PrDetectionClass', on_delete=models.PROTECT)
    """(ForeignKey) the PR Vehicle Detection class identified \(:class:`psa.models.PrDetectionClass`\)"""
    
    prediction_class = models.ForeignKey('psa.PredictionClass', on_delete=models.PROTECT)
    """(ForeignKey) the Prediction class identified \(:class:`psa.models.PredictionClass`\)"""
    
    license_plate_number = models.CharField(max_length=8)
    """(CharField) The license plate number"""
    
    dominant_colour = models.ForeignKey('psa.Colour', on_delete=models.PROTECT)
    """(ForeignKey) the dominant colour of the vehicle \(:class:`psa.models.Colour`\)"""
    
    dominant_colour_detected_by_iai = models.BooleanField(default=False, help_text='Was the dominant colour detected by Imageai analysis?')
    """(BooleanField) whether or not the dominant colour was detected during Imageai analysis, deafults to False"""
    
    dominant_colour_identified_as_dominant_by_iai = models.BooleanField(blank=True, null=True,help_text='Was the dominant colour identified as the dominant colour by Imageai analysis?')
    """(BooleanField) whether or not the dominant colour was identified as dominant during Imageai analysis"""
    
    dominant_colour_detected_by_pr = models.BooleanField(default=False, help_text='Was the dominant colour detected by Plate Recognizer analysis?')
    """(BooleanField) whether or not the dominant colour was detected during PR analysis, deafults to False"""
    
    dominant_colour_identified_as_dominant_by_pr = models.BooleanField(blank=True, null=True,help_text='Was the dominant colour identified as the dominant colour by Plate Recognizer analysis?')
    """(BooleanField) whether or not the dominant colour was identified as dominant during PR analysis"""
    
    image_angle = models.ForeignKey('psa.ImageAngle',on_delete=models.CASCADE)
    """(ForeignKey) the angle of the object in the image \(:class:`psa.models.ImageAngle`\)"""
    
    iai_extract_correct = models.BooleanField(blank=True, null=True,help_text='Did IAI extract the correct object?')
    """(BooleanField) whether or not the correct object was extracted during Imageai analysis"""
    
    iai_extract_entire = models.BooleanField(blank=True, null=True,help_text='Did IAI extract the entire object?')
    """(BooleanField) whether or not the entire object was extracted during Imageai analysis"""
    
    pr_extract_correct = models.BooleanField(blank=True, null=True,help_text='Did PR extract the correct object?')
    """(BooleanField) whether or not the correct object was extracted during PR analysis"""
    
    pr_extract_entire = models.BooleanField(blank=True, null=True,help_text='Did PR extract the entire object?')
    """(BooleanField) whether or not the entire object was extracted during PR analysis"""
    
    plate_extract_correct = models.BooleanField(blank=True, null=True,help_text='Did PR extract the correct plate?')
    """(BooleanField) whether or not the correct plate was extracted during PR analysis"""
    
    plate_extract_entire = models.BooleanField(blank=True, null=True,help_text='Did PR extract the entire plate?')
    """(BooleanField) whether or not the entire plate was extracted during PR analysis"""
    


    class Meta:
        """Adds metadata about the PrColourDetection model class (used in admin section)
        """ 
        
        verbose_name = 'manual analysis'
        """(str) the name of the model class"""
        
        verbose_name_plural = 'manual analyses'
        """(str) the plural version of the name of the model class"""
        

    def __str__(self):
        """Returns the string representation of the object

        :return: the string representation of the object (manual analysis' entry's arrival time) 
                 (format = '%I:%M:%S %p' = 
                 Hour (12-hour clock) as a zero-padded decimal number : Minute as a zero-padded decimal number : Second as a zero-padded decimal number : either AM or PM)  
        :rtype: str
        """

        return self.entry.arrival_time.strftime('%I:%M:%S %p')

    def get_absolute_url(self):
        return reverse('manual-entry-detail', kwargs={'pk' : self.entry.pk})


class GetManualContext():
    """Gets the context data the form views need
    """
    def get_manual_context(entry):
        """Gets the title of the page and performs queries to get the data needed for the dropdown select inputs

        :param entry: The entry that the manual analysis is associated with \(:class:`analysis.models.Entry`\)  
        :type entry: Entry  
        :return: a dictionary containing the title and all the needed data  
        :rtype: dict  
        """
        response = {}

        if entry.status == 'complete':
            response['title'] = f'Update {entry.day.date.strftime("%b %d, %Y")}, {entry} Manual Analysis'
        else:
            response['title'] = f'Make {entry.day.date.strftime("%b %d, %Y")}, {entry} Manual Analysis'
        
        response['entry'] = entry

        iai_auto_colour_names = []
        iai_auto_colour_percentages = {}
        iai_auto_colour_detected_r = {}
        iai_auto_colour_detected_g = {}
        iai_auto_colour_detected_b = {}
        iai_auto_colour_detected_hex = {}
        iai_auto_colour_chart_colours = {}
        for colour in entry.automatedanalysis.iaicolourdetections.order_by('-percentage'):
            iai_auto_colour_names.append(colour.colour.name)
            iai_auto_colour_percentages[colour.colour.name] = float(colour.percentage)
            iai_auto_colour_detected_r[colour.colour.name] = colour.detected_r
            iai_auto_colour_detected_g[colour.colour.name] = colour.detected_g
            iai_auto_colour_detected_b[colour.colour.name] = colour.detected_b
            iai_auto_colour_detected_hex[colour.colour.name] = colour.detected_hex
            iai_auto_colour_chart_colours[colour.colour.name] = f'rgb({colour.colour.r}, {colour.colour.g}, {colour.colour.b})'

        pr_auto_colour_names = []
        pr_auto_colour_percentages = {}
        pr_auto_colour_detected_r = {}
        pr_auto_colour_detected_g = {}
        pr_auto_colour_detected_b = {}
        pr_auto_colour_detected_hex = {}
        pr_auto_colour_chart_colours = {}
        for colour in entry.automatedanalysis.prcolourdetections.order_by('-percentage'):
            pr_auto_colour_names.append(colour.colour.name)
            pr_auto_colour_percentages[colour.colour.name] = float(colour.percentage)
            pr_auto_colour_detected_r[colour.colour.name] = colour.detected_r
            pr_auto_colour_detected_g[colour.colour.name] = colour.detected_g
            pr_auto_colour_detected_b[colour.colour.name] = colour.detected_b
            pr_auto_colour_detected_hex[colour.colour.name] = colour.detected_hex
            pr_auto_colour_chart_colours[colour.colour.name] = f'rgb({colour.colour.r}, {colour.colour.g}, {colour.colour.b})'


        response['iai_auto_colour_names'] = iai_auto_colour_names
        response['iai_auto_colour_percentages'] = iai_auto_colour_percentages
        response['iai_auto_colour_detected_r'] = iai_auto_colour_detected_r
        response['iai_auto_colour_detected_g'] = iai_auto_colour_detected_g
        response['iai_auto_colour_detected_b'] = iai_auto_colour_detected_b
        response['iai_auto_colour_detected_hex'] = iai_auto_colour_detected_hex
        response['iai_auto_colour_chart_colours'] = iai_auto_colour_chart_colours

        response['pr_auto_colour_names'] = pr_auto_colour_names
        response['pr_auto_colour_percentages'] = pr_auto_colour_percentages
        response['pr_auto_colour_detected_r'] = pr_auto_colour_detected_r
        response['pr_auto_colour_detected_g'] = pr_auto_colour_detected_g
        response['pr_auto_colour_detected_b'] = pr_auto_colour_detected_b
        response['pr_auto_colour_detected_hex'] = pr_auto_colour_detected_hex
        response['pr_auto_colour_chart_colours'] = pr_auto_colour_chart_colours

        return response

manual/templates/manual/day_detail.html
{% extends "psa/layouts/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load index %}

{% block head_content %}
    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    
{% endblock head_content %}

{% block content %} 

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%  url 'psa-home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'analysis-home' %}">Analysis</a></li>
            <li class="breadcrumb-item"><a href="{%  url 'manual-home' %}">Manual Analyses</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ day.date|date:"F j, Y" }}</li>
        </ol>
    </nav>

    <div class="card bg-light">
        <div class="card-header row align-items-center">
            {% with tables|index:0 as table %}
                <div class="col" >
                    <h2>
                        {{ day.date|date:"F j, Y" }} Manual Summary 

                        {% if day.tried_feed_in %}
                            (tried feed in) 
                        {% else %}
                            (didn't try feed in) 
                        {% endif %}

                        ({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})
                    </h2>
                </div>
            {% endwith %}

            <div class="text-right">
                <a href="{% url 'analysis-day-detail' day.id %}" class="btn btn-sm btn-info" title='View Analysis Summaries'><i class="fas fa-eye"></i><i class="far fa-eye"></i></i></a>
                <a href="{% url 'automated-day-detail' day.id %}" class="btn btn-sm btn-primary" title='View All Automated Analyses'><i class="fas fa-eye"></i></a>
                <a href="{% url 'analysis_statistics-home' %}?date_after={{ day.date|date:'Y-m-d' }}&date_before={{ day.date|date:'Y-m-d' }}" class="btn btn-sm btn-secondary" title='View Statistics'><i class="fas fa-chart-bar"></i></a>
                <a href="{% url 'psa-open-file' day.json_file.url %}" target="_blank" class="btn btn-sm btn-secondary" title='View JSON'><i class="fas fa-file"></i></a>
                <a href="{% url 'psa-open-file' day.log_file.url %}" class="btn btn-sm btn-secondary" title='View Log'><i class="far fa-file"></i></a>
            </div>
        </div>            
        
        <div class="card-body">
            <ul class="nav nav-tabs nav-justified" id="analysisDayDetailTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="entry-info-tab" data-toggle="tab" href="#entry-info" role="tab" aria-controls="entry-info" aria-selected="true">Entry Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="entry-timing-tab" data-toggle="tab" href="#entry-timing" role="tab" aria-controls="entry-timing" aria-selected="false">Entry Timing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="day-timing-tab" data-toggle="tab" href="#day-timing" role="tab" aria-controls="day-timing" aria-selected="false">Day Timing</a>
                </li>
            </ul>


            <div class="tab-content" id="manualDayDetailTabContent">
                
                <div class="tab-pane fade show active" id="entry-info" role="tabpanel" aria-labelledby="entry-info-tab">
                    {% if filter %}
                        <form action="" method="get" class="form form-inline">
                            {{ filter.form|crispy }}
                            <a href="{%  url 'manual-day-detail' day.id %}">Clear all filters</a>
                            <input type="submit" />
                        </form>
                    {% endif %}
                    
                    {% with tables|index:0 as table %}
                        {% if table != None %}
                            {%  render_table table %}
                            
                            <div class="text-center">
                                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
                            </div>
                                
                        {% else %}
                            <h2>NO DATA</h2>
                        {% endif %}
                    {% endwith %}
                </div>

                <div class="tab-pane fade" id="entry-timing" role="tabpanel" aria-labelledby="entry-timing-tab">
                    {% with tables|index:1 as table %}
                        {% if table != None %}
                            {%  render_table table %}
                            
                            <div class="text-center">
                                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
                            </div>
                                
                        {% else %}
                            <h2>NO DATA</h2>
                        {% endif %}
                    {% endwith %}
                </div> 

                <div class="tab-pane fade" id="day-timing" role="tabpanel" aria-labelledby="day-timing-tab">
                    {% include 'psa/partials/day_timing_section.html' %}
                </div>

            </div>

        </div>
    </div>


{% endblock content %}

{% block script_content %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    
    <script>
        $(document).ready(function() {
            function formatColour (colour) {
                var name = colour.text.replace(/ /g,'')
                var $colour = $(
                    '<span class="row fluid mx-auto"> <span class="little-box col" style="background:'+ name +'"></span> <span class="col">' + colour.text + '</span> </span>'
                );
                return $colour;
            };

            $('#id_successful_feed_in').select2();
            $('#id_iaivehicledetection').select2();
            $('#id_prvehicledetection').select2();
            $('#id_prediction').select2();
            $('#id_dominant_colour').select2( { templateResult: formatColour } );
            $('#id_dominant_colour_detected_by_iai').select2();
            $('#id_dominant_colour_identified_as_dominant_by_iai').select2();
            $('#id_dominant_colour_detected_by_pr').select2();
            $('#id_dominant_colour_identified_as_dominant_by_pr').select2();
            $('#id_image_angle').select2();
            $('#id_iai_extract_correct').select2();
            $('#id_pr_extract_correct').select2();
            $('#id_plate_extract_correct').select2();
        });
    </script>
{% endblock script_content%}

manual/templates/manual/entry_detail.html
{% extends "psa/layouts/base.html" %}
{% block content %} 

	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{%  url 'psa-home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'analysis-home' %}">Analysis</a></li>
			<li class="breadcrumb-item"><a href="{%  url 'manual-home' %}">Manual Analyses</a></li>
			<li class="breadcrumb-item"><a href="{%  url 'manual-day-detail' object.day.id %}">{{ object.day.date|date:"F j, Y" }}</a></li>
			<li class="breadcrumb-item active" aria-current="page">{{ object.arrival_time|time:"g:i:s a" }}</li>
		</ol>
	</nav>
	<div class="row">

	</div>

	<div class="row">		

		<div class="ml-0 col-md-6">
			{% include 'psa/partials/image_section.html' %}
		</div>

		<div class="col-md-6">
			<div class="card bg-light">
				<div class="card-header row align-items-center">
					<div class="col" ><h2>{{ object.arrival_time|date:"F j, Y, g:i:s a" }} Manual Analysis</h2></div>
					<div class="text-right">
						<a href="{% url 'analysis-entry-detail' object.id %}" class="btn btn-sm btn-info" title='View Analysis Summary'><i class="fas fa-eye"></i><i class="far fa-eye"></i></i></a>
						<a href="{% url 'automated-entry-detail' object.id %}" class="btn btn-sm btn-primary" title='View Automated Analysis'><i class="fas fa-eye"></i></a>
						<a href="{% url 'manual-update' object.id %}" class="btn btn-sm btn-secondary" title='Update Manual Analysis'><i class="fas fa-edit"></i></a>
					</div>
				</div>            
				
				<div class="card-body">
					<ul class="nav nav-tabs nav-justified" id="myInfoTab" role="tablist">
						<li class="nav-item">
							<a class="nav-link active" id="basic-tab" data-toggle="tab" href="#basic" role="tab" aria-controls="basic" aria-selected="true">Basic</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" id="iai-tab" data-toggle="tab" href="#iai" role="tab" aria-controls="iai" aria-selected="false">IAI</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" id="pr-tab" data-toggle="tab" href="#pr" role="tab" aria-controls="pr" aria-selected="false">PR</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" id="license-plate-tab" data-toggle="tab" href="#license-plate" role="tab" aria-controls="license-plate" aria-selected="false">License Plate</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" id="timing-tab" data-toggle="tab" href="#timing" role="tab" aria-controls="timing" aria-selected="false">Timing</a>
						</li>
					</ul>
					
					<div class="tab-content" id="myInfoTabContent">
						<div class="tab-pane fade show active" id="basic" role="tabpanel" aria-labelledby="basic-tab">
							{% include 'psa/partials/entry_basic.html' with entry_context='manual' %}
						</div>
						
						<div class="tab-pane fade" id="iai" role="tabpanel" aria-labelledby="iai-tab">
							{% include 'psa/partials/iai_manual_div.html' %}
						</div>

						<div class="tab-pane fade" id="pr" role="tabpanel" aria-labelledby="pr-tab">
							{% include 'psa/partials/pr_manual_div.html' %}
						</div>

						<div class="tab-pane fade" id="license-plate" role="tabpanel" aria-labelledby="license-plate-tab">
							{% include 'psa/partials/plate_manual_div.html' %}
						</div>

						<div class="tab-pane fade" id="timing" role="tabpanel" aria-labelledby="timing-tab">
							{% include 'psa/partials/entry_timing_div.html' %}
						</div>

				</div>
			</div>			
		</div>
		
	</div>
{% endblock content %}

manual/templates/manual/home.html
{% extends "psa/layouts/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}

{% block head_content %}
    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    
{% endblock head_content %}


{% block content %} 

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%  url 'psa-home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'analysis-home' %}">Analysis</a></li>
            <li class="breadcrumb-item active" aria-current="page">Manual Analyses</li>
        </ol>
    </nav>

    <div class="card bg-light">
        <div class="card-header row align-items-center">
            <div class="col" ><h2>Manual Analysis Home ({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h2></div>

            <div class="ml-2 col text-right">
                <a href="{% url 'analysis-home' %}" class="btn btn-sm btn-info" title='View All Analyses'><i class="fas fa-eye"></i><i class="far fa-eye"></i></a>
                <a href="{% url 'automated-home' %}" class="btn btn-sm btn-primary" title='View All Auto Analyses'><i class="fas fa-eye"></i></a>
                <a href="{% url 'analysis_statistics-home' %}" class="btn btn-sm btn-secondary" title='View All Statistics'><i class="fas fa-chart-bar"></i></a>
            </div>

        </div>            
        
        <div class="card-body">
            {% if filter %}
                <form action="" method="get" class="form form-inline">
                    {{ filter.form|crispy }}
                    <a href="{%  url 'manual-home' %}">Clear all filters</a>
                    <input type="submit" />
                </form>
            {% endif %}

            {% if table != None %}
                {%  render_table table %}
            {% else %}
                <h2>NO DATA</h2>
            {% endif %}

            <div class="text-center">
                <h3>({{ table.rows|length }} {% if table.rows|length == 1 %}entry{% else %}entries{% endif %})</h3>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script_content %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    
    <script>
        $(document).ready(function() {
            function formatColour (colour) {
                var name = colour.text.replace(/ /g,'')
                var $colour = $(
                    '<span class="row fluid mx-auto"> <span class="little-box col" style="background:'+ name +'"></span> <span class="col">' + colour.text + '</span> </span>'
                );
                return $colour;
            };

            $('#id_tried_feed_in').select2();
            $('#id_successful_feed_in').select2();
            $('#id_iaivehicledetection').select2();
            $('#id_prvehicledetection').select2();
            $('#id_prediction').select2();
            $('#id_dominant_colour').select2( { templateResult: formatColour } );
            $('#id_dominant_colour_detected_by_iai').select2();
            $('#id_dominant_colour_identified_as_dominant_by_iai').select2();
            $('#id_dominant_colour_detected_by_pr').select2();
            $('#id_dominant_colour_identified_as_dominant_by_pr').select2();
            $('#id_image_angle').select2();
            $('#id_iai_extract_correct').select2();
            $('#id_pr_extract_correct').select2();
            $('#id_plate_extract_correct').select2();
        });
    </script>
{% endblock script_content%}